# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

pool: selfhosted

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: wolfw00xd/logs-app
        tags: |
          $(tag)
    - script: |
        docker ps -a
        docker images
        docker run -d --name qqqq wolfw00xd/logs-app:$(tag)
        docker ps -a
        docker cp  qqqq:/opt/app/need.txt .
        cat need.txt
    - script: |
        curl -D- \
          -H "Authorization:Basic dmFzeWwub3duZXJAZ2E0aS5jb206QVRBVFQzeEZmR0YwYW45WHdkSFVvbkxLbG4xZGxIUFR1T2dGbjh4cTFMRHJ0ZFpzbmhFcU9BdWp6UjhxT2gzQkROTWluUVgya3JtbUMyNFJDMTdPd3Z4ekdTMk4zVDh4ajBWaDhTWW1fVUlhNDBucmF6QmU0NFJaMHFKZEFSSkNUR240MHdJU3lTVVZEVXd6U1g1N0pwOURucmF1RWRqWTNXRHAwNXNnanp6c0pGV1Z0WUFERDQ4PTA2QzY2RDky" \
          -X POST \
          -H 'X-Atlassian-Token: nocheck' \
          -F 'file=@"need.txt"' \
          -F 'minorEdit="true"' \
          -F 'comment="Example attachment comment"; type=text/plain; charset=utf-8' \
          --url 'https://ga4i.atlassian.net//wiki/rest/api/content/7929857/child/attachment'
        

