# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

pool: selfhosted

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: wolfw00xd/logs-app
        tags: |
          $(tag)
    - script: |
        docker ps -a
        docker images
        docker run -v $PWD:/opt/mount --rm --entrypoint cp wolfw00xd/logs-app:$(tag) /opt/app/need.txt /opt/mount/need.txt
        docker ps -a
        cat need.txt
    - script: |
        curl -D- \
        -H "Authorization:Basic $(TOKEN)" \
        -X PUT \
        -H 'X-Atlassian-Token: nocheck' \
        -F 'file=@"need.txt"' \
        -F 'minorEdit="true"' \
        -F 'comment="Example attachment comment"; type=text/plain; charset=utf-8' \
        --url 'https://ga4i.atlassian.net/wiki/rest/api/content/9535489/child/attachment'

