# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

pool: selfhosted

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: wolfw00xd/logs-app
        tags: |
          $(tag)
    - script: |
        docker ps -a
        docker images
        docker run -d --name $(Build.BuildId) wolfw00xd/logs-app:$(tag)
        docker ps -a
        docker cp  $(Build.BuildId):/opt/app/need.txt .
        cat need.txt
    - script: |
        echo $(Build.BuildId) > data1
        sed -z 's/\n/\\n/g' need.txt >> data1
        data=$(cat data1)
        version=$(curl -H "Authorization:Basic $(TOKEN)" -X GET "https://ga4i.atlassian.net/wiki/api/v2/pages/7929857/" | jq -r '.version.number')
        newversion=$((version+1))
        curl -D- -H "Content-Type:application/json" -H "Authorization:Basic $(TOKEN)" -X PUT --data "{\"id\":\"7929857\",\"type\":\"page\",\"title\":\"test pipeline\",\"space\":{\"key\":\"ga4i\"},\"body\":{\"storage\":{\"value\":\"$data\",\"representation\":\"storage\"}},\"version\":{\"number\":\"$newversion\"}}" https://ga4i.atlassian.net/wiki/rest/api/content/7929857
        
        

